# Transformaciones

La mayoría de las series de tiempo no son débilmente estacionarias, es decir que no muestran una media ni una varianza constantes a lo largo del tiempo y pueden mostrar tendencias crecientes o bien, decrecientes. Para poder trabajar con este tipo de series de una forma más sencilla y manejable, existen métodos para transformarlas y verlas como realizaciones de una serie de tiempo débilmente estacionaria. Las transformaciones más comunes son el suavizamiento a través de medias móviles o ajustando polinomios a la serie en cuestión, la diferenciación.

## Suavizamiento por medias móviles

Se mencionó que las series de tiempo se pueden ver como la suma de tres componentes: una tendencia, una estacionalidad y una componente aleatorio o irregular. Ahora bien, en este método de suavizamiento el objetivo es estimar y extraer **la tendencia** $\left(T_t\right)$ del modelo. Lo anterior se puede realizar estimando la tendencia con: 

$$
\hat T_t=(2q+1)^{-1}\sum_{j=-q}^q X_{t-j},\space q+1\leq t\leq n-q
$$

Este es uno de mucho filtros lineales que podrían aplicarse ($\hat T_t=\sum_{j=-\infty}^\infty a_jX_{t-j}$). Obsérvese que para valores grandes de $q$, $(2q+1)^{-1}\sum_{j=-q}^q [X_{t-j}-\hat T_t]\approx 0$, lo cual no sólo atenua el ruido, también permite que la tendencia lineal $T_t=c_0+c_1t$ pase sin distorsión. Sin embargo hay que tener cuidado en la selección de $q$, ya que valores muy grandes, si $T_t$ no es lineal, entonces se suavizará la serie pero la estimación de la tendencia será mala.

## Suavizamiento por polinomios ajustados

En este método de suavizamiento el objetivo es estimar y extraer la **tendencia** ($T_t$) y la **estacionalidad** ($E_t$) del modelo. Si $E_t= 0$, se tiene un caso de no estacionariedad simple, por lo que el proceso tiene un comportamiento estacionario alrededor de la tendencia y para estimar $T_t$ se supone que tiene la siguiente forma:

$$
T_t = a_0 + a_1 +... + a_pt^p
$$

Si se tiene $p = 1$ la tendencia es lineal, si $p = 2$ la tendencia es cuadrática.

Los parámetros $a_i$ se estiman mediante mínimos cuadrados ordinarios, es decir que minimicen $\sum_{i=1}^n (x_i-T_i)^2$.

## Diferencias de Box-Jenkins

Consiste en aplicar diferencias a la serie de tiempo estudiada hasta que las observaciones se perciban como componentes de una serie débilmente estacionaria. Se debe comprender los siguientes operadores para el método: 

El **operador de retraso** se denota con una letra $B$ o $\mathcal{L}$ y se define como el valor retrasado de una serie de tiempo temporal indicado por el exponente del operador. De manera particular se tiene $BX_t = X_{t-1}$, por lo que si se aplica varias veces el operador, la serie se retardaría $k$-unidades temporales:

$$
B^kX_t=X_{t-k}
$$

En particular $B^0X_t=X_t$. Se puede utilizar con notación polinómica:

$$
\phi(B)X_t = \left(\phi_0+\phi_1B+\phi_2B^2\right)X_t = \phi_0X_t+\phi_1X_{t-1}+\phi_2X_{t-2} 
$$

El **operador diferencia** se expresa con $\nabla$ y se define como la diferencia entre el valor al periodo $t$ y valor rezagado $k$ periodos $\nabla X_t=X_t-X_{t-1}$.

Ambos operadores se relacionan de la siguiente manera: 

$$
\nabla Z_t=Z_t-Z_{t-1}=Z_t-BZ_t=(1-B)Z_t
$$
Teniendo que $\nabla=(1-B)$ 
Si aplicamos el operador diferencia sucesivamente entonces se obtiene:


$$
\begin{array}{cc}
\nabla^k=(1-B)^k; & \nabla^kX_t=\sum_{j=0}^k\frac{k!}{k!(k-1)!}(-1)^kX_{t-k}
\end{array}
$$